Update Folder module2_task5

diff --git a/module2_task5/Makefile b/module2_task5/Makefile
--- a/module2_task5/Makefile
+++ b/module2_task5/Makefile
@@ -1,40 +1,44 @@
-integration-tests: ## 
-	@go test -v -coverprofile=coverage-integrations.out
-
-unit-tests: ## Runs unit tests in order to test the code
-	@go test -v -short -coverprofile=coverage-units.out
-
-lint: ## Runs a lint tool
-	@golangci-lint run *.go
-
-check: ## Runs a lint for the md and an analysis of the links
-	@markdownlint 'content/**/*.md'
-	@find ./content -name \*.md -print0 | xargs -0 -n1 markdown-link-check
-
-validate: ## Validates the syntax of the index.html in the dist directory
-	@./w3c_validator.py ./dist/index.html || true
-
-build: lint check ## Generate the website from markdown
-	@hugo
-	@go build -o awesome-api ./*.go
-
-run: ## Run the application
-	@./awesome-api >./awesome.log 2>&1 &
-
-stop: ## Stop the app
-	@pkill awesome-api || true
-
-clean: stop ## Cleanup the content of the 'dist/' folder
-	@rm -rf dist/
-	@rm -f awesome-api awesome.log
-	@rm -f coverage-units.out coverage-integrations.out
-
-test: unit-tests integration-tests ## Tests the application
-	@echo "Test"
-
-post: ## Create a new blog post using POST_TITLE and POST_NAME env variables
-	hugo new posts/$(POST_NAME).md
-	sed -i '/title:/c\title: "$(POST_TITLE)"' content/posts/$(POST_NAME).md
-
-help: ## Show this help.
+help:           ## Show this help.
 	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
+
+build:     ## Generate a website and an API application.
+	@go build
+	@hugo > /dev/null 2>&1
+
+run:            ## Run the application in background, and write logs into a file named awesome-api.log
+	@make build
+	./awesome-api > ./awesome-api.log 2>&1 &
+
+lint:           ## Does the linting of the program using golangci-lint
+	/root/go/bin/golangci-lint run
+
+stop:           ## Stop the application
+	pkill awesome-api
+
+clean:          ## Cleanup the content of the directory dist/ and stop the application. Delete the binary awesome-api and the log file awesome-api.log
+	pkill awesome-api || true
+	rm -rf awesome-api awesome-api.log coverage-units.out coverage-integrations.out
+	rm -rf dist/*
+
+post:           ## Create a new blog post
+	hugo new posts/$(POST_NAME).md
+	sed -i 's/title: .*/title: "$(POST_TITLE)"/' content/posts/$(PO
+	ST_NAME).md
+
+test:          ## Tests for browser responses
+	make unit-tests
+	make integration-tests
+	make validate
+
+unit-tests:    ## Execute (successfully) the Golang unit tests
+	go test -v -short -coverprofile=coverage-units.out
+
+integration-tests:     ## Execute (successfully) the Golang integration tests
+	go test -v -tags=integration -coverprofile=coverage-integrations.out
+
+check:         ## Check if there are dead link or a badly written Markdown file
+	markdownlint ./content/posts/*.md
+	markdown-link-check ./content/posts/*.md
+
+validate:      ## look if the generated HTML respects the W3C syntax
+	python3 /opt/W3C-Validator/w3c_validator.py ./dist/index.html || true
